package:
  name: ''
  author: ''
  author_email: ''
  year: '2023'
  description: ''
  urls:
    main: ''
    documentation: ''
    source: ''
  keywords: []
  install_requires: []
documentation:
  logo: ''
  favicon: ''
  language: en
options:
  logging: false
  git: false
  gui: false
gui:
  splash: true
