package:
  name: ''
  author: ''
  author_email: ''
  year: '2021'
  description: ''
  urls:
    main: ''
    documentation: ''
    source: ''
  keywords: []
  install_requires: []
documentation:
  logo: ''
  favicon: ''
options:
  logging: false
  git: false
